### ISSUE TITLE
Run pyflakes

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/yank#129] opened 2014-11-25 17:07 UTC
Lots of unused imports, unused code, possible bugs could be fixed by a round of pyflakes.

**Comment by bas-rustenburg** [comment] 2015-01-09 17:19
Any use for a tool such as landscape.io?

**Comment by kyleabeauchamp** [comment] 2015-01-09 17:25
Let's do it manually for now, this is something that only needs to happen twice a year IMHO

**Comment by bas-rustenburg** [comment] 2015-01-09 17:59
Ok! Has this been done since the issue was opened?

**Comment by kyleabeauchamp** [comment] 2015-01-09 18:00
No, but it doesn't make sense to run pyflakes until we finish all the large scale code changes that are pending.  I generally run pyflakes when we're closer to a release.

**Comment by bas-rustenburg** [comment] 2015-01-09 18:02
Understood.

**Comment by jchodera** [comment] 2015-01-09 19:51
Marking this as `yank 1.0` so we remember to run this once before release.

**Comment by jchodera** [comment] 2015-01-22 23:21
Duplicate of #13.

**Closed by jchodera** 2015-01-22 23:21 UTC
