### ISSUE TITLE
Add YAML options to specify whether to expand cutoff and how large to set the expanded cutoff

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#615] opened 2016-12-27 17:09 UTC
I'm running into some trouble completing hydration free energy calculations.

It would be great if we could add a YAML option to specify whether to expand the cutoff and, if so, how large to set the expanded cutoff.

We'd want these options to be used instead of hardcoded logic in [this code](https://github.com/choderalab/yank/blob/master/Yank/yank.py#L383-L430).

**Comment by Lnaden** [comment] 2016-12-27 17:17
This is one of the things I left in as a "to-do" which is why the `expand_cutoff` was accepted as a kwarg in that nested function so we could eventual modify it later.

**Comment by andrrizzi** [comment] 2016-12-30 09:41
Closing this because duplicate of #483. Feel free to reopen if I missed the point.

**Closed by andrrizzi** 2016-12-30 09:41 UTC
