### ISSUE TITLE
tleap error with implicit solvent example

### ISSUE THREAD

**Issue by drthock** [choderalab/yank#447] opened 2016-08-14 01:15 UTC
I'm trying to run an implicit-water free energy calc, and am running into the following error: 

``````
2016-08-13 18:08:40,242: MPI disabled.
2016-08-13 18:08:40,245: Setting up the systems for 4djw, E5BCED and OBC2
Traceback (most recent call last):
  File "/home/yanker/miniconda2/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.1.dev0', 'console_scripts', 'yank')()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/cli.py", line 118, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 41, in dispatch
    yaml_builder.build_experiments()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1278, in build_experiments
    self._setup_experiments()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 2006, in _setup_experiments
    self._db.get_system(system_id)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 667, in get_system
    ligand_id)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1079, in _setup_system
    warnings = tleap.run()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank-0.9.1.dev0-py2.7-linux-x86_64.egg/yank/utils.py", line 1386, in run
    leap_output = subprocess.check_output(['tleap', '-f', 'leap.in'])
  File "/home/yanker/miniconda2/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Com
```mand '['tleap', '-f', 'leap.in']' returned non-zero exit status 1
yanker@turing:~/redo$
``````

I've tried my best to neutralize and assign bond orders for both the protein and ligand, but I'm getting a somewhat nondescript tleap error. I've attached my input here. Do you have any idea as to what the problem/solution might be? 

[yank.zip](https://github.com/choderalab/yank/files/416837/yank.zip)

**Comment by jchodera** [comment] 2016-08-14 03:39
Thanks for reporting this!

Your problem brings attention to the fact that we don't currently have a good way of passing on LEaP failure logs to the user to help debug what the issue is. I'll create an issue to remind us to find a way to do this.

By running the `setup/systems/4djw/complex.leap.in` script through `tleap` manually, the error appears to be:
```
Creating new UNIT for residue: TLA sequence: 839
Created a new atom named: H within residue: .R<TLA 839>
Bond: Maximum coordination exceeded on .R<GLY 449>.A<H 2>
      -- setting atoms pert=true overrides default limits
ATOMS NOT BONDED: .R<NGLY 58>.A<N 1> .R<GLY 449>.A<H 2>
!FATAL ERROR----------------------------------------
!FATAL:    In file [atom.c], line 445
!FATAL:    Message: bondAtomProblem found
!
!ABORTING.
```
The RCSB residue [`TLA`](http://www.rcsb.org/pdb/ligand/ligandsummary.do?hetId=TLA) is a cosolvent (L(+)-tartaric acid) that presumably has no parameters in the AMBER forcefield you've selected.

In addition, you have a lot of hydrogens that have been added at the end of the file, and this is somehow being perceived by `tleap` as a whole series of new residues for which it is trying to add heavy atoms.

I'd suggest you try to clean your protein file further:
* Remove all cosolvents
* Remove the protons---they will be added by `tleap`. 

Also, please remember that this version of YANK is still **highly experimental** and there is no guarantee of accuracy or correctness at this stage! We are still writing all of the validation tests to ensure accuracy and correctness in advance of a 1.0 release!

**Comment by Lnaden** [comment] 2016-11-08 18:42
It looks like there may have been a syntax or input file issue there. We have a few issues open to improve the general output from tleap setup processes that should hopefully make failures more helpful in the future. 

Thank you for reporting this issue, Im going to close this issue now as I think some other open ones will address this as we find them, but if you are still having problems, please feel free to open another!

**Closed by Lnaden** 2016-11-08 18:42 UTC
