### ISSUE TITLE
Maximum number of NAN retries (6) exceeded

### ISSUE THREAD

**Issue by GerardBCN** [choderalab/yank#577] opened 2016-11-23 09:29 UTC
What can I do to fix this issue?

```
Iteration 26 / 100
2016-11-23 10:26:46,780: Mixing replicas...

[...]

2016-11-23 10:27:06,327: NaN detected in replica 18. Retrying (1 / 6).
2016-11-23 10:27:07,254: NaN detected in replica 18. Retrying (2 / 6).
2016-11-23 10:27:08,176: NaN detected in replica 18. Retrying (3 / 6).
2016-11-23 10:27:09,104: NaN detected in replica 18. Retrying (4 / 6).
2016-11-23 10:27:10,038: NaN detected in replica 18. Retrying (5 / 6).

[...]

Exception: Maximum number of NAN retries (6) exceeded.


```

**Comment by GerardBCN** [comment] 2016-11-23 14:52
after few 3 experiment runs, I got to the 100 iterations without this type of error. I guess is quite an sparse and irreproducible error

**Comment by andrrizzi** [comment] 2016-11-23 15:55
Hi @GerardBCN. Do you know on which platform you are running YANK? At the beginning of the log file, there should be a line similar to
```
Setting CUDA platform to use precision model 'mixed'.
```
This is a problem that we are facing too when using the OpenCL platform, but almost never happened to me with the CUDA platform. We are trying to collect more data to understand the problem, and we are working with the OpenMM devs to solve it.

**Comment by jchodera** [comment] 2016-11-23 16:01
Which version of OpenMM are you using?

**Comment by jchodera** [comment] 2016-11-23 16:01
And on which GPU hardware, CUDA version, and driver version?

**Comment by jchodera** [comment] 2016-11-23 16:31
We're tracking down some OpenMM problems related to `nan`s as well (which may be related to driver issues):

cc: https://github.com/pandegroup/openmm/issues/1651 https://github.com/pandegroup/openmm/issues/1666

**Comment by GerardBCN** [comment] 2016-11-24 09:53
I'm using (conda list openmm):

openmm                    7.0.1                    py35_0    omnia

I will try with a computer with a GPU well set up, this one doesn't even work for simulations. 

About the NaNs, seems quite an irreproducible error, because after several retries, computation finally can go on without errors.

**Comment by andrrizzi** [comment] 2016-11-25 20:28
If you are using the OpenCL platform as I suspect, this problem could be related to this openmm bug: pandegroup/openmm#1676

**Comment by andrrizzi** [comment] 2016-11-25 22:23
Ah! But I notice now you were using openmm 7.0.1, of course, so disregard my last comment.

**Comment by spadavec** [comment] 2017-01-24 17:44
I'm getting this issue as well about ~1/3 of the time. 

```
distro: ubuntu (16.04) 
driver: 367.57
card(s): GTX 1080
openmm: 7.2.0 
yank --v: 0.14.1 
platform: CUDA
precision: mixed
``` 

and the yaml file, if thats at all relevant: 

```
experiments:
  protocol: absolute-binding
  restraint: type: Boresch
  system: mcl1
molecules:
  mcl1: filepath: mcl1.pdb
  C00CFB:
    antechamber: charge_method: bcc
    filepath: C00CFB.mol2
options: minimize: true, nsteps_per_iteration: 500, number_of_iterations: 1000, output_dir: .,
  platform: CUDA, pressure: 1*atmosphere, resume_setup: true, resume_simulation: true,
  temperature: 300*kelvin, timestep: 1.5*femtoseconds, verbose: true
protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_electrostatics: [1.0, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55,
          0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0]
        lambda_restraints: [0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.5, 0.75, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        lambda_sterics: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0, 1.0, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55,
          0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.075, 0.05, 0.025, 0.01,
          0.0]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.0, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6, 0.55,
          0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.05, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0]
        lambda_sterics: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.95, 0.9, 0.85, 0.8, 0.75,
          0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3, 0.25, 0.2, 0.15, 0.1, 0.0]
solvents:
  pme: clearance: 12*angstroms, ewald_error_tolerance: 0.0001, negative_ion: Cl-,
    nonbonded_cutoff: 12*angstroms, nonbonded_method: PME, positive_ion: Na+, switch_distance: 11*angstroms
systems:
  mcl1:
    leap:
      parameters: [leaprc.protein.ff14SB, leaprc.gaff, leaprc.water.tip3p]
    ligand: C00CFB
    receptor: mcl1
    solvent: pme 
```

**Comment by jchodera** [comment] 2017-01-24 18:57
We're adding some debug code to write out serialized XML files when NaNs are encountered to facilitate debugging. That will let you send those---along with a PDB file of the complex---to us to aid in tracking down the NaNs.

Does the same thing happen with OpenCL?

**Comment by spadavec** [comment] 2017-01-24 19:39
@jchodera I've yet to run these with with ```OpenCL``` yet, as it would take (likely?) days to get to the point where it fails reliably (and we're using these machines to run ~10 calculations at at time, so we've been favoring CUDA :) ). However, if that would be useful for debugging this issue, I would be more than happy to do that.

**Comment by jchodera** [comment] 2017-01-24 19:41
Do you have input files you could share where we could try to reproduce the problem?

**Comment by spadavec** [comment] 2017-01-24 20:58
Sure thing--I've attached the files here (yaml, pdb, mo2). 

[issue_551.zip](https://github.com/choderalab/yank/files/727929/issue_551.zip)

I was able to run this exact file set on an earlier version of yank (I want to say 0.9?), albeit with a different YAML syntax (i.e. harmonic restraints, no pme, and perhaps *slightly* less aggressive lambas) that was accurate to ~1.5kcal.

**Comment by Lnaden** [comment] 2017-01-24 21:07
Thanks! I'll start trying to debug this. We have been trying to help deploy a new OpenMM version built off CUDA 8.0 instead of 7.5, which has caused a large number of seemingly random NaN's and other problems, especially on the 10XX cards (from CUDA 7.5), and older cards (from CUDA 8.0). Its probably why this worked just fine on the older version of YANK before we started this new deploy.

**Comment by Lnaden** [comment] 2017-01-26 15:30
@spadavec Could you provide the git hash for your OpenMM version.

```python
import simtk.openmm as mm
mm.version.version
```

It will look something like `7.1.0.dev-9567ddb`. Don't worry if the output number says 7.1.0, we really just need the hash at the end to check which code version you are running on.

**Comment by spadavec** [comment] 2017-01-27 17:41
@Lnaden, sorry for the long response time! Hash is: 

```7.1.0.dev-02e7a5d```

**Comment by Lnaden** [comment] 2017-01-30 18:34
@spadavec I can't seem to recreate this on our cluster here with the files you provided. I'm also only running this on 1 card (unrelated issue with our cluster preventing me from running on more than 1 with CUDA atm). So I am going to try to whittle down sources of differences.

* Are you using MPI to run across multiple cards? 
* Can you provide the `.log` file when the error crashed which should be in your output folder in another folder called `experiments`? Its a plain text file of all the output, so it may be a bit large and have to be zipped up as well.

**Comment by spadavec** [comment] 2017-01-30 18:53
@Lnaden ah, thats unfortunate about not being able to reproduce the issue! 

> Are you using MPI to run across multiple cards?

No. We are currently running 3-4 jobs/gpu in 'serial' mode--(side note: we are currently running 2 1080 GTXs with 1 i7 6700k, which leads me to believe the bottleneck in speed would be with the CPU, so running in MPI mode wouldn't really help, right?) 

> Can you provide the .log file when the error crashed which should be in your output folder in another folder called experiments? Its a plain text file of all the output, so it may be a bit large and have to be zipped up as well.

Absolutely! I've attached [here](https://github.com/choderalab/yank/files/739928/experiments-log.zip) for your review. I'm currently re-running this job in triplicate on another machine to see if I can replicate the issue again for you.

**Comment by Lnaden** [comment] 2017-01-30 18:58
@spadavec It may also be worth using this debug branch of yank shown in #629 to trap helpful output in case it does actually throw a NaN

**Comment by spadavec** [comment] 2017-01-31 21:58
@Lnaden sorry for the confusion, but it looks like those fixes got introduced in the ```master``` branch, so I should be able to just clone that branch all those changes will be included, correct?

**Comment by Lnaden** [comment] 2017-01-31 22:17
Yes. Sorry for the confusion, we decided to go ahead and just merge those changes in as we thought they would be generally helpful, you should just be able to use master

**Comment by Lnaden** [comment] 2017-02-02 14:46
@spadavec Any luck recreating the NaN? Just checking so we can help the OpenMM 7.1 release

**Comment by spadavec** [comment] 2017-02-02 18:58
@Lnaden sorry for the delays! I should be able to start the job later today, which means I should be able to see a failure (hopefully) by tomorrow night, or thereabouts.

**Comment by spadavec** [comment] 2017-02-03 03:41
@Lnaden looks like we got lucky and the job failed quickly! 

Tail of the logfile: 

```
2017-02-02 19:22:44,909: Replica 24/40: integrator elapsed time 1.290 s (positions 0.027 s | velocities 0.110 s | integrate+getstate 1.061 s).
2017-02-02 19:22:46,658: Replica 25/40: integrator elapsed time 1.257 s (positions 0.027 s | velocities 0.111 s | integrate+getstate 1.025 s).
2017-02-02 19:22:48,382: Replica 26/40: integrator elapsed time 1.227 s (positions 0.027 s | velocities 0.170 s | integrate+getstate 0.937 s).
2017-02-02 19:22:50,110: Replica 27/40: integrator elapsed time 1.558 s (positions 0.030 s | velocities 0.112 s | integrate+getstate 1.324 s).
2017-02-02 19:22:52,434: NaN detected in replica 28. Retrying (1 / 6).
Traceback (most recent call last):
  File "/home/yanker/miniconda2/bin/yank", line 11, in <module>
    load_entry_point('yank==0.15.0', 'console_scripts', 'yank')()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/commands/script.py", line 100, in dispatch
    yaml_builder.build_experiments()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 1333, in build_experiments
    self._run_experiment(combination, output_dir)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yamlbuild.py", line 2528, in _run_experiment
    yank.run()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/yank.py", line 584, in run
    simulation.run(niterations_to_run=niterations_to_run)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/repex.py", line 878, in run
    self._propagate_replicas()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/sampling.py", line 828, in _propagate_replicas
    ReplicaExchange._propagate_replicas(self)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/repex.py", line 1357, in _propagate_replicas
    self._propagate_replicas_serial()
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/repex.py", line 1339, in _propagate_replicas_serial
    self._propagate_replica(replica_index)
  File "/home/yanker/miniconda2/lib/python2.7/site-packages/yank/sampling.py", line 784, in _propagate_replica
    from yank.utils import serialize_openmm_object_to_file
ImportError: No module named utils

```
Interestingly enough, I can import the `utils` module from my interpreter directly, so it might be the case that I have a PATH (or some other environment variable) set incorrectly. 

I've attached the logfile [here](https://github.com/choderalab/yank/files/749525/experiments.zip) for your review. I updated my installation, so relevant info: 

```
openmm git hash: 7.1.0.dev-02e7a5d
yank version: 0.15.0
```

**Comment by spadavec** [comment] 2017-02-03 03:57
it looks like theres the following directories: 

```
yank
yank-0.15.0-py2.7-linux-86_64.egg-info
```

ouput of ls: 

```
yanker@turing:~/miniconda2/lib/python2.7/site-packages$ ls -ltr yank*
yank-0.15.0-py2.7-linux-x86_64.egg-info:
total 32
-rw-rw-r-- 2 yanker yanker    5 Feb  1 11:42 top_level.txt
-rw-rw-r-- 2 yanker yanker 3836 Feb  1 11:42 SOURCES.txt
-rw-rw-r-- 2 yanker yanker   95 Feb  1 11:42 requires.txt
-rw-rw-r-- 2 yanker yanker  992 Feb  1 11:42 PKG-INFO
-rw-rw-r-- 2 yanker yanker    1 Feb  1 11:42 not-zip-safe
-rw-rw-r-- 2 yanker yanker   29 Feb  1 11:42 native_libs.txt
-rw-rw-r-- 2 yanker yanker   40 Feb  1 11:42 entry_points.txt
-rw-rw-r-- 2 yanker yanker    1 Feb  1 11:42 dependency_links.txt

yank:
total 964
-rw-rw-r-- 2 yanker yanker  31909 Feb  1 11:42 yank.py
-rw-rw-r-- 2 yanker yanker 110382 Feb  1 11:42 yamlbuild.py
-rw-rw-r-- 2 yanker yanker    363 Feb  1 11:42 version.pyc
-rw-rw-r-- 2 yanker yanker    237 Feb  1 11:42 version.py
-rw-rw-r-- 2 yanker yanker  58715 Feb  1 11:42 utils.pyc
-rw-rw-r-- 2 yanker yanker  62002 Feb  1 11:42 utils.py
-rw-rw-r-- 2 yanker yanker  45079 Feb  1 11:42 systembuilder.py
-rw-rw-r-- 2 yanker yanker  50881 Feb  1 11:42 sampling.py
-rw-rw-r-- 2 yanker yanker  45785 Feb  1 11:42 restraints.py
-rw-rw-r-- 2 yanker yanker 122136 Feb  1 11:42 repex.py
-rw-rw-r-- 2 yanker yanker  16496 Feb  1 11:42 pipeline.py
-rw-rw-r-- 2 yanker yanker    602 Feb  1 11:42 __init__.pyc
-rw-rw-r-- 2 yanker yanker    450 Feb  1 11:42 __init__.py
-rw-rw-r-- 2 yanker yanker   1890 Feb  1 11:42 cli.pyc
-rw-rw-r-- 2 yanker yanker   2978 Feb  1 11:42 cli.py
-rw-rw-r-- 2 yanker yanker  19279 Feb  1 11:42 analyze.pyc
-rw-rw-r-- 2 yanker yanker  27206 Feb  1 11:42 analyze.py
-rw-rw-r-- 2 yanker yanker  21613 Feb  1 11:42 yank.pyc
-rw-rw-r-- 2 yanker yanker  81084 Feb  1 11:42 yamlbuild.pyc
-rw-rw-r-- 2 yanker yanker  37290 Feb  1 11:42 systembuilder.pyc
-rw-rw-r-- 2 yanker yanker  32686 Feb  1 11:42 sampling.pyc
-rw-rw-r-- 2 yanker yanker  41221 Feb  1 11:42 restraints.pyc
-rw-rw-r-- 2 yanker yanker  90367 Feb  1 11:42 repex.pyc
-rw-rw-r-- 2 yanker yanker  13983 Feb  1 11:42 pipeline.pyc
drwxrwxr-x 2 yanker yanker   4096 Feb  2 15:54 mixing
drwxrwxr-x 2 yanker yanker   4096 Feb  2 15:54 commands
drwxrwxr-x 3 yanker yanker   4096 Feb  2 15:54 tests

```
I think I've been pretty careful about having only 1 installation on this user, but its entirely possible? I do have a few other users on this machine (for production runs and debugging) which also have their own miniconda/yank installations. Could that be making things a bit murky? Condas pkg handling has always confused me a little

**Comment by jchodera** [comment] 2017-02-03 04:00
> it looks like theres the following directories:

Hm, that's all as expected.

**Comment by jchodera** [comment] 2017-02-03 04:03
@Lnaden : Should this be `from .utils import serialize_openmm_object_to_file` instead of `from yank.utils import serialize_openmm_object_to_file`? I thought absolute paths were OK for both py 2 and 3.

**Comment by Lnaden** [comment] 2017-02-03 04:24
@jchodera I have had issues with absolute paths in general for internal imports unless you are explicitly doing testing. So the `from .utils import...` would be the better call.

@spadavec Question, did you ever `pip install` YANK? I have had some really unexpected behavior with doing a pip and conda install at different times. Otherwise to make a quick fix instead of waiting for us to push a fix, change that line to 

```python
from .utils import serialize_openmm_object_to_file
```

There might also be something we are not catching at the Python 2.7 SWIG wrapper causing issues? But all versions should both be using the same underlying C++ OpenMM code, so idk what is going on. All my debugging was on Python 3.5, so its the only thing different between our tests I can think of.

**Comment by Lnaden** [comment] 2017-02-03 04:25
I'll restart my tests on python 2.7 tonight and see if I can trap it

**Comment by spadavec** [comment] 2017-02-03 04:38
@Lnaden I don't think I've ever used `pip install` for yank (but I can't rule it out 100%). I'll make the change you suggested and re-run the job now; I should have an update for you soon. Sorry for being a py2.7 heathen; I just can't seem to force myself to make the jump yet :)

**Comment by Lnaden** [comment] 2017-02-03 04:45
We still support it, so its fine. If you have never used pip, that's probably also fine. The time stamps don't indicate there is a `.pyc` file overruling a `.py` file which is why I asked. We'll see if one of us can trap this error by morning.

**Comment by spadavec** [comment] 2017-02-03 16:27
[iteration serialization output here](https://github.com/choderalab/yank/files/751001/iteration182-replica7-state1-nan.zip)

**Comment by Lnaden** [comment] 2017-02-03 18:11
Neat, I can pass that info on once i do some local debugging.

**Comment by Lnaden** [comment] 2017-02-03 18:50
@spadavec What version of `alchemy` are you using? `conda list alchemy` should be sufficient.

**Comment by spadavec** [comment] 2017-02-03 18:54
@Lnaden 
'''
alchemy                   1.2.0                    py27_0    omnia
'''

**Comment by Lnaden** [comment] 2017-02-03 19:23
Ohhhhhh.... I think thats the problem. We have put in a large number of bug fixes to the `alchemy` module and are now up at 1.2.3. I imagine there are actually energy bugs related to the your system coming out of that, which is probably why I can't regenerate it unless I had your system to load (it preserves all the energy expressions `alchemy` generates.)

YANK does not require a specific `alchemy` version, so every time you installed it probably just detected the old version and thought that was sufficient.

I'm willing to bet if you update your alchemy version (`conda install -c omnia alchemy`) and start the simulations over, the crash would stop. You actually will have to start them over, not just resume since resuming does not rebuild the alchemical systems, it just reads the existing system much like the files you handed off to us.

**Comment by spadavec** [comment] 2017-02-03 19:33
well, thats a little embarrassing for me! I'll update and re-run the job now. Thanks for the tip!

**Comment by spadavec** [comment] 2017-02-06 16:37
It looks like upgrading `alchemy` did the trick. The job completed, although it took ~35% longer and was off by ~7kcal/mol. In any case, thanks for all the help!

**Comment by jchodera** [comment] 2017-02-06 16:44
> The job completed, although it took ~35% longer 

Interesting! Between 1.2.0 and 1.2.1, @andrrizzi overhauled the treatment of exceptions. I'm surprised that this results in such a large degradation in performance on the same platform. We'll look into this.

> and was off by ~7kcal/mol. 

Off from experiment, or off from previous results?

**Comment by spadavec** [comment] 2017-02-06 18:05
@jchodera Along side this calculation, I ran 8 other calculations as part of a battery of tests and they all took 35-50% longer than previous versions of yank/alchemy; I did use different ligand constraints (Boresch vs. harmonic) and a different solvent method (pme), but I dont suspect those would cause such a dramatic increase in time to run? 

> Off from experiment, or off from previous results?

Both. Reported literature value is -7.7 kcal/mol, and yank consistently reported appx. -8.0 - 8.5kcal/mol. This time it clocked in at -1.7. I'm gonna whip together a script to  visualize the trajectories to make sure that nothing crazy is going on, but a quick glance at the ```yank analyze``` output shows the warning

```
Found expanded cutoff states in the energies!
2017-02-06 8:53:47,090: Free energies will be reported relative to them instead!
2017-02-06 8:53:47,090: Computing free energy differences...
````

**Comment by jchodera** [comment] 2017-02-06 18:25
> I did use different ligand constraints (Boresch vs. harmonic) and a different solvent method (pme), but I dont suspect those would cause such a dramatic increase in time to run?

What solvent method were you using previously? PME is much slower than alternative methods:
http://openmm.org/about.html#benchmarks

> Both. Reported literature value is -7.7 kcal/mol, and yank consistently reported appx. -8.0 - 8.5kcal/mol. This time it clocked in at -1.7. I'm gonna whip together a script to visualize the trajectories to make sure that nothing crazy is going on, but a quick glance at the yank analyze output shows the warning

Can you post the full output of `yank analyze`? It could be that the cutoff expansion is actually significantly perturbing the free energy or causing a lot of uncertainty to be introduced.

**Comment by Lnaden** [comment] 2017-02-06 18:28
What was the solvent you were using before `PME`? And what version of YANK are you comparing the speed difference too? The files you provided us were already using the Boresch restraints and PME, so this must have been much earlier, yes?

The Boresch restraint should not add that much overhead, its a single compound bond between 6 atoms. PME will add some cost if you are switching from say Reaction Field and very much so if you are switching from implicit solvent.

The version of YANK you were running where the expanded cutoff states has been in since 0.14.1. We added those additional states [to correct for finite box effects](http://getyank.org/0.15.0/theory.html) to some extent (link goes to our theory page explaining it). I wanted to know what version of YANK you were running before since this is something you have not seen before.

As for the difference in Free Energy. I'm first basing this on the MCL1 and the C00CFB molecule. Do you have the ligand already in a binding pose with the receptor to start? The Boresch Orientational restraints apply to the starting pose of the molecules and try to keep them there as the simulation advances. If you started somewhere that was not in the binding site, the molecule will likely never find the site since its been oritentationally restrained somewhere else.

**Comment by spadavec** [comment] 2017-02-06 18:42
@jchodera 

What solvent method were you using previously? PME is much slower than alternative methods:
http://openmm.org/about.html#benchmarks

I was using RF before; I thought PME would be slower but didn't realize it was benchmarked at 1/3 slower. 

> Can you post the full output of yank analyze? It could be that the cutoff expansion is actually significantly perturbing the free energy or causing a lot of uncertainty to be introduced.

Attached the output here [here](https://github.com/choderalab/yank/files/755526/yank-analyze.zip)

@Lnaden 

> The version of YANK you were running where the expanded cutoff states has been in since 0.14.1. We added those additional states to correct for finite box effects to some extent (link goes to our theory page explaining it). I wanted to know what version of YANK you were running before since this is something you have not seen before.

Ah, ok. I'll have to dig around and see if I have old log files laying around, but I think the version we were using prior to this upgrade was 0.9.x. Let me see what I can dig up and get back to you on that. 

> As for the difference in Free Energy. I'm first basing this on the MCL1 and the C00CFB molecule. Do you have the ligand already in a binding pose with the receptor to start? The Boresch Orientational restraints apply to the starting pose of the molecules and try to keep them there as the simulation advances. If you started somewhere that was not in the binding site, the molecule will likely never find the site since its been oritentationally restrained somewhere else.

This system is the output of a docking program, but its quite similar to the xtal structure (I think its accurate to ~0.1 A)

**Comment by jchodera** [comment] 2017-02-06 19:08
PME also can produce different free energies from RF. We're trying to quantify these differences and see if there's a way to minimize them to match the "gold standard" of PME.

**Comment by jariwalask** [comment] 2017-02-24 22:48
I am seeing the same issue, ~1/5 times when running in serial on GPU:

`
distro: RHEL 6.4 
driver: 375.26
card(s): GTX 680
openmm: 7.0.1 (compiled)
yank --v: 0.14.1 
platform: CUDA
precision: mixed
alchemy: 1.2.3 (py27_0    omnia)
`
Is an update to openmm 7.1.0  + yank 0.15 recommended for this issue?

**Comment by jchodera** [comment] 2017-02-25 01:28
I would definitely recommend updating to the latest YANK and `openmm`.

If you do see `NaN`s again, please send us some of the serialized XML files that are produced by 0.15.0 when this happens. You can zip them up.

**Comment by jariwalask** [comment] 2017-02-25 04:15
@jchodera Will update and report back. On a side-note, in cases where `NaN`s are encountered, I am planning on re-running with `resume_simulation : yes` in the yaml file. Would you recommend on running the simulation from scratch?

**Comment by jchodera** [comment] 2017-02-25 04:23
If you can resume successfully, it should be OK to resume!

**Comment by jariwalask** [comment] 2017-03-06 19:37
As an update, `resume_simulation : yes` did not work. Same `NaN`s encountered. The GPU card and NVIDIA version were different:

```
distro: RHEL 6.4 
driver: 367.48 (versus 375.26)
card(s): GTX 780 (versus GTX 680)
openmm: 7.0.1 (compiled)
yank --v: 0.14.1 
platform: CUDA
precision: mixed
alchemy: 1.2.3 (py27_0    omnia)
```

The openmm and yank version were the same. Simulations with updated 7.1.0 + yank 0.15 are running, and will update with success/error. Thanks

**Comment by jchodera** [comment] 2017-03-06 19:40
Thanks! It will be useful to get the serialized XML files generated when you run into NaNs with 7.1.0rc1

**Comment by jchodera** [comment] 2017-09-04 16:25
Closing this presuming we no longer have these issues. Please reopen if needed!

**Closed by jchodera** 2017-09-04 16:25 UTC
