### ISSUE TITLE
Allow extract-trajectory to handle trajectories with 1 frame

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/yank#635] opened 2017-02-03 23:54 UTC
The extract trajectory functionality seems to need its help updated. I was trying to use `yank analyze extract-trajectory` to, er, extract a trajectory and I kept getting usage information feedback when I seemed to be doing something legit:

```
yank analyze extract-trajectory --netcdf=output/experiments/solvent1.nc --trajectory=solvent1.pdb
Usage:
  yank analyze (-s STORE | --store=STORE) [-v | --verbose]
  yank analyze extract-trajectory --netcdf=FILEPATH (--state=STATE | --replica=REPLICA) --trajectory=FILEPATH [--start=START_FRAME] [--skip=SKIP_FRAME] [--end=END_FRAME]
```

After poking around for a bit, I established that apparently `--replica` is a required argument. So after adding that, I get:

```
yank analyze extract-trajectory --netcdf=output/experiments/solvent1.nc --trajectory=solvent1.pdb --replica=0
2017-02-03 15:49:58,580: Detected periodic boundary conditions: True
2017-02-03 15:49:58,581: Number of iterations: 1, atoms: 5406
Traceback (most recent call last):
  File "/home/dmobley/anaconda3/bin/yank", line 11, in <module>
    load_entry_point('yank==0.15.0.dev0', 'console_scripts', 'yank')()
  File "/home/dmobley/anaconda3/lib/python3.5/site-packages/yank-0.15.0.dev0-py3.5-linux-x86_64.egg/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/dmobley/anaconda3/lib/python3.5/site-packages/yank-0.15.0.dev0-py3.5-linux-x86_64.egg/yank/commands/analyze.py", line 63, in dispatch
    return dispatch_extract_trajectory(args)
  File "/home/dmobley/anaconda3/lib/python3.5/site-packages/yank-0.15.0.dev0-py3.5-linux-x86_64.egg/yank/commands/analyze.py", line 97, in dispatch_extract_trajectory
    analyze.extract_trajectory(output_path, nc_path, **kwargs)
  File "/home/dmobley/anaconda3/lib/python3.5/site-packages/yank-0.15.0.dev0-py3.5-linux-x86_64.egg/yank/analyze.py", line 643, in extract_trajectory
    raise ValueError('No frames selected')
ValueError: No frames selected
```

So apparently I'm required to also select specific frames. 

Probably it would be a good idea to make the usage information indicate that these are required.

In my specific case, I'm trying to troubleshoot a crash very early by inspecting the trajectories. If I attempt to analyze frames 0 to 2, I get an `IndexError`, and if I attempt to analyze frames 0 to 1, it tells me I have selected no frames. Probably this is a separate issue.

**Comment by andrrizzi** [comment] 2017-02-04 15:31
Hi David, thanks for reporting!

The help string is actually correct. The syntax `(--state=STATE | --replica=REPLICA)` is standard for mutually exclusive required arguments. The frames selected are not required arguments and I think that your error is caused by shortage of iterations. The second line of the output is
```
2017-02-03 15:49:58,581: Number of iterations: 1, atoms: 5406
```
which means that the simulation crashed right after the minimization. The function currently discards this frame because it creates problems with the automatic equilibration detection. I'll add an exception to this behavior in case that is the only frame requested in the next few days.

**Comment by jchodera** [comment] 2017-02-04 15:42
We're also in the process of updating everything to use the newly released OpenMM 7.1 and recent `alchemy` bugfix releases---both of which greatly improve stability.

**Comment by davidlmobley** [comment] 2017-02-04 16:32
@andrrizzi :
> The help string is actually correct. The syntax (--state=STATE | --replica=REPLICA) is standard for mutually exclusive required arguments.

OK. I think I must not be used to using command-line tools which use this format; I thought the parents meant those are optional arguments. 

> 2017-02-03 15:49:58,581: Number of iterations: 1, atoms: 5406
> which means that the simulation crashed right after the minimization. The function currently discards this frame because it creates problems with the automatic equilibration detection.

I was trying to troubleshoot a case where minimization truncates early and the simulation terminates immediately. @jchodera had suggested I turn off minimization, run a short simulation,  and visualize the frames to see if I could tell what was wrong with the setup (as far as I can tell, nothing, since it runs fine in other codes and ALSO runs fine if I minimize on CPU rather than GPU before putting it into Yank). In any case, it turns out not to be useful to do so here since I don't actually get back any frames that I can visualize since it crashes too rapidly.

This can be closed, I suppose.

**Comment by jchodera** [comment] 2017-02-04 16:45
> OK. I think I must not be used to using command-line tools which use this format; I thought the parents meant those are optional arguments.

We use the excellent [`docopt`](http://docopt.org/) for handling the CLI. Check it out---it describes the format.

**Comment by jchodera** [comment] 2017-02-04 16:46
> I was trying to troubleshoot a case where minimization truncates early and the simulation terminates immediately. @jchodera had suggested I turn off minimization, run a short simulation, and visualize the frames to see if I could tell what was wrong with the setup (as far as I can tell, nothing, since it runs fine in other codes and ALSO runs fine if I minimize on CPU rather than GPU before putting it into Yank). In any case, it turns out not to be useful to do so here since I don't actually get back any frames that I can visualize since it crashes too rapidly.

Which openmm version are you using, and which version of `alchemy` do you have installed?

For openmm:
```python
>>> print(simtk.openmm.version.version)
7.0.1.dev-5e86c4f
```
For alchemy:
```bash
lski1962:conda-recipes.jchodera choderaj$ conda list | grep alchemy
alchemy                   1.2.3                    py35_0    omnia
```

**Comment by davidlmobley** [comment] 2017-02-05 04:25
@jchodera - I have `alchemy` as follows:
```
[dmobley@gplogin3 ~]$ conda list | grep alchemy
alchemy                   1.2.3                    py35_0    omnia
```

For openmm:
```
>>> print(simtk.openmm.version.version)
7.1.0.dev-9500f3a
```

**Comment by jchodera** [comment] 2017-02-05 04:28
[This fix](https://github.com/pandegroup/openmm/pull/1726) was merged into `openmm` after that commit, and may be responsible if those conditions are met in your case. I'd upgrade to the official `openmm==7.1.0` in the `omnia` channel and see if that helps.

**Comment by davidlmobley** [comment] 2017-02-05 04:30
That doesn't apply in my case, @jchodera - this is just a generic SMIRNOFF system so there is no custom nonbonded force applied. However, I'll re-try with the release 7.1, probably on Monday.

**Comment by andrrizzi** [comment] 2017-02-05 16:18
I'll reopen this as a reminder to implement the extraction of the first frame too.

**Comment by jchodera** [comment] 2017-02-05 17:57
> That doesn't apply in my case, @jchodera - this is just a generic SMIRNOFF system so there is no custom nonbonded force applied. However, I'll re-try with the release 7.1, probably on Monday.

@davidlmobley : If you're performing an alchemical free energy calculation, it's creating custom forces under the hood.

**Comment by davidlmobley** [comment] 2017-02-06 19:08
@jchodera - thanks! That does actually seem to be helping. I'll report back.

**Comment by davidlmobley** [comment] 2017-02-06 19:10
@jchodera - also, have you looked at how much this bug affects solvation free energy calculations? I'd done some work for the SMIRNOFF paper attempting some solvation free energy calculations, and I'm assuming this means all solvation free energy calculations would need to be repeated (if done with incorrect box vectors)?

**Comment by jchodera** [comment] 2017-02-06 21:15
> @jchodera - also, have you looked at how much this bug affects solvation free energy calculations? I'd done some work for the SMIRNOFF paper attempting some solvation free energy calculations, and I'm assuming this means all solvation free energy calculations would need to be repeated (if done with incorrect box vectors)?

Incorrect box vectors?

**Comment by davidlmobley** [comment] 2017-02-06 21:16
@jchodera - yes, the incorrect box vector bug; have you looked at how much it affects solvation free energy calculations?

**Comment by jchodera** [comment] 2017-02-06 21:26
Oh! You mean the bug fixed in https://github.com/pandegroup/openmm/pull/1726. I would imagine this would necessitate the calculations be repeated for safety, though I recall we seemed to get good agreement even without this fix. 

We're working on automating the validation tests so we can whitelist releases as being verified to produce previous publication data. Things are obviously still in flux at the moment.

**Comment by jchodera** [comment] 2017-09-04 16:06
Closing this. Please reopen if this issue is unresolved.

**Comment by andrrizzi** [comment] 2017-09-04 20:59
It's not resolved yet actually. The function automatically discards the first frame, so it's still not possible to extract the minimized/equilibrated structure.

**Closed** 2018-05-03 18:37 UTC
