### ISSUE TITLE
Modify charged host-guest examples to use DSL to specify ligand as guest PLUS counterion once DSL implemented

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#166] opened 2015-01-12 22:27 UTC
Once #161 is implemented, we want to specify the ligand in the host-guest calculations as a neutral species of guest *PLUS* counterion.

**Comment by andrrizzi** [comment] 2016-07-18 22:14
Duplicate of #345 and implemented in #350. Closing.

**Closed by andrrizzi** 2016-07-18 22:14 UTC
