### ISSUE TITLE
Solubility

### ISSUE THREAD

**Issue by kadiliissaar** [choderalab/yank#1217] opened 2020-03-31 19:59 UTC
Hello!

Could people please recommend what might be best way to use yank to predict solubilities? Something similar to the hydration energy estimation and look at the free energy differences between the solvated state and the salt? How to best describe the salt?

Thank you and best wishes,
Kadi

**Comment by andrrizzi** [comment] 2020-04-04 15:10
Closing as I think this is a duplicate of #1221 .

**Closed by andrrizzi** 2020-04-04 15:10 UTC
