### ISSUE TITLE
Installation with conda problems

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/yank#175] opened 2015-01-13 00:47 UTC
The installation with conda now creates the binary file in "anaconda/bin/yank", but any call to it raise

Traceback (most recent call last):
  File "/home/andrrizzi/anaconda/bin/yank", line 4, in <module>
    from yank.cli import main
ImportError: No module named yank.cli

I am not sure whether the old installation through "yank/setup.py" left an environment variable set somewhere that is messing up with the new installation. What I did was removing completely the anaconda folder, reinstall anaconda and then run "conda install yank".

**Comment by bas-rustenburg** [comment] 2015-01-13 15:18
I can confirm that I also get this bug with a clean installation. I'm using the channel:
http://conda.binstar.org/omnia/linux-64/

I don't think the package is set up correctly at the moment. This is what my installation looks like:

```
├── bin
│   └── yank
├── info
│   ├── files
│   ├── has_prefix
│   ├── index.json
│   ├── recipe
│   │   ├── build.sh
│   │   ├── meta.yaml
│   │   └── meta.yaml.orig
│   └── recipe.json
└── lib
    └── python2.7
        └── site-packages
            ├── openmmtools
            │   ├── data
            │   │   ├── alanine-dipeptide-explicit
            │   │   │   ├── alanine-dipeptide.crd
            │   │   │   ├── alanine-dipeptide.pdb
            │   │   │   ├── alanine-dipeptide.prmtop
            │   │   │   ├── leap.log
            │   │   │   ├── run.sh
            │   │   │   └── setup.leap.in
            │   │   ├── alanine-dipeptide-gbsa
            │   │   │   ├── alanine-dipeptide.crd
            │   │   │   ├── alanine-dipeptide.pdb
            │   │   │   ├── alanine-dipeptide.prmtop
            │   │   │   ├── leap.log
            │   │   │   ├── README
            │   │   │   ├── run.sh
            │   │   │   └── setup.leap.in
            │   │   ├── amoeba
            │   │   │   ├── 1AP4_14_wat.pdb
            │   │   │   └── ion-in-water.pdb
            │   │   ├── methanol-box
            │   │   │   ├── methanol-box.crd
            │   │   │   ├── methanol-box.pdb
            │   │   │   ├── methanol-box.prmtop
            │   │   │   └── README
            │   │   ├── src-explicit
            │   │   │   ├── state.xml
            │   │   │   └── system.xml
            │   │   ├── src-implicit
            │   │   │   └── implicit-refined.pdb
            │   │   ├── T4-lysozyme-L99A-implicit
            │   │   │   ├── complex.crd
            │   │   │   ├── complex-minimized.crd
            │   │   │   ├── complex-min.sander.out
            │   │   │   ├── complex.pdb
            │   │   │   ├── complex.prmtop
            │   │   │   ├── complex-testenergy.sander.out
            │   │   │   ├── leap.log
            │   │   │   ├── ligand.crd
            │   │   │   ├── ligand.frcmod
            │   │   │   ├── ligand-minimized.crd
            │   │   │   ├── ligand-min.sander.out
            │   │   │   ├── ligand.mol2
            │   │   │   ├── ligand.pdb
            │   │   │   ├── ligand.prmtop
            │   │   │   ├── ligand-testenergy.sander.out
            │   │   │   ├── ligand.tripos.mol2
            │   │   │   ├── mdinfo
            │   │   │   ├── min.sander.in
            │   │   │   ├── receptor.crd
            │   │   │   ├── receptor-minimized.crd
            │   │   │   ├── receptor-min.sander.out
            │   │   │   ├── receptor.pdb
            │   │   │   ├── receptor.prmtop
            │   │   │   ├── receptor-testenergy.sander.out
            │   │   │   ├── setup.leap.in
            │   │   │   ├── setup.leap.out
            │   │   │   └── testenergy.sander.in
            │   │   ├── trpzip2-explicit
            │   │   │   ├── README
            │   │   │   ├── trpzip2.crd
            │   │   │   └── trpzip2.prmtop
            │   │   └── waterbox
            │   │       ├── tip3p900.pdb
            │   │       ├── watbox216.crd
            │   │       ├── watbox216.pdb
            │   │       └── watbox216.prmtop
            │   ├── __init__.py
            │   ├── __init__.pyc
            │   ├── integrators.py
            │   ├── integrators.pyc
            │   ├── tests
            │   │   ├── test_integrators.py
            │   │   ├── test_integrators.pyc
            │   │   ├── test_testsystems.py
            │   │   └── test_testsystems.pyc
            │   ├── testsystems.py
            │   ├── testsystems.pyc
            │   ├── version.py
            │   └── version.pyc
            └── openmmtools-0.9.0-py2.7.egg-info

18 directories, 77 files
```

**Comment by jchodera** [comment] 2015-01-13 15:21
Thanks!  Looks like all the `yank` stuff besides `bin/yank` isn't actually making it into the repo.  I'll see if I can fix this ASAP.

**Comment by bas-rustenburg** [comment] 2015-01-13 15:26
I also think that there might be a bunch of `.pyc` files being included by accident. Might be good to clean those up.

**Comment by kyleabeauchamp** [comment] 2015-01-13 15:35
OK, the openmmtools being included can be fixed by following the changes Robert made the the openmm recipe (https://github.com/omnia-md/conda-recipes/blob/master/openmm/meta.yaml)

**Comment by jchodera** [comment] 2015-01-13 17:33
@kyleabeauchamp Did you change the conda recipe to try to fix this?  If so, can you make a note?  I started to work on this and realized you changed the recipe 2 hours ago...

**Comment by kyleabeauchamp** [comment] 2015-01-13 17:45
I made two pull requests to the conda-recipes repository.  See https://github.com/omnia-md/conda-recipes/pull/111 and https://github.com/omnia-md/conda-recipes/pull/112

I'm still not sure if this will fix the issues, as I'm still waiting for the jenkins builds, which may take some time.

**Comment by jchodera** [comment] 2015-01-22 21:08
We think this is resolved

**Closed by jchodera** 2015-01-22 21:08 UTC
