### ISSUE TITLE
analysis_particle_indices warning

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#902] opened 2018-03-03 05:15 UTC
I've run into this warning on the `sams` branch. Is it something to worry about?
```
2018-03-03 00:15:05,998: Single node: executing <function ExperimentBuilder._save_analysis_script at 0x7f197e73aea0>
2018-03-03 00:15:06,001: Initial checkpoint file automatically chosen as explicit/experiments/complex_checkpoint.nc
2018-03-03 00:15:06,165: analysis_particle_indices != on-file analysis_particle_indices!Using on file analysis indices of [   0    1    2 ... 4341 4342 4343]
2018-03-03 00:15:06,169: Initial checkpoint file automatically chosen as explicit/experiments/complex_checkpoint.nc
2018-03-03 00:15:06,210: analysis_particle_indices != on-file analysis_particle_indices!Using on file analysis indices of [   0    1    2 ... 4341 4342 4343]
2018-03-03 00:15:06,215: Initial checkpoint file automatically chosen as explicit/experiments/complex_checkpoint.nc
2018-03-03 00:15:06,255: analysis_particle_indices != on-file analysis_particle_indices!Using on file analysis indices of [   0    1    2 ... 4341 4342 4343]
2018-03-03 00:15:06,259: Initial checkpoint file automatically chosen as explicit/experiments/complex_checkpoint.nc
2018-03-03 00:15:06,299: analysis_particle_indices != on-file analysis_particle_indices!Using on file analysis indices of [   0    1    2 ... 4341 4342 4343]
```

**Comment by Lnaden** [comment] 2018-03-03 12:14
In most cases no, that usually happens when you try to resume a simulation because the from_storage call does not set the `analysis_particle_indices` keyword, so it just allows the on-file one to be used. Since the analysis particles are really only set through the pipeline. I could not figure out a simple way to set them on resume, and just decided to let the warning raise, and use the on-file ones.

**Comment by Lnaden** [comment] 2018-03-12 13:13
I'm closing this as its expected behavior from resume. If its actually a problem, we can re-open it

**Closed by Lnaden** 2018-03-12 13:13 UTC
