### ISSUE TITLE
Problem in running AMBER prepared solvated protein ligand complex

### ISSUE THREAD

**Issue by mmagithub** [choderalab/yank#716] opened 2017-07-14 15:26 UTC
HI,
I am new to YANK and having trouble running absolute-binding protocol on a system that was prepared with AMBER and should work according to the instructions provided online.
Here is my yaml script:
##########
---
options:
  minimize: yes
  verbose: yes
  output_dir: .
  number_of_iterations: 5
  nsteps_per_iteration: 1000
  temperature: 300*kelvin
  pressure: 1*atmosphere
  timestep: 1.5*femtoseconds
  output_dir: explicit

systems:
  bms-135:
    phase1_path:: [input/bms_135_yank_com.inpcrd,input/bms_135_yank_com.prmtop]
    phase2_path: [input/bms_135_yank_sol.inpcrd,input/bms_135_yank_sol.prmtop]
    ligand_dsl: resid 231
    solvent_dsl: resname WAT 
    solvent: PME-solvent

solvents:
  PME-solvent:
    nonbonded_method: PME
    nonbonded_cutoff: 10*angstrom
    clearance: 12*angstroms

protocols:
  absolute-binding:
    complex:
      alchemical_path:
        lambda_restraints:     [0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.50, 0.75, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.000, 1.00, 1.000, 1.00, 1.00]
        lambda_electrostatics: [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.000, 0.00, 0.000, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.075, 0.05, 0.025, 0.01, 0.00]
    solvent:
      alchemical_path:
        lambda_electrostatics: [1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00]
        lambda_sterics:        [1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.00]

experiments:
  system: bms-135
  protocol: absolute-binding
  restraint:
    type: Boresch
##########
Whenever I run this file, I got this error:
2017-07-14 09:16:59,304: Setting OpenCL platform to use precision model 'mixed'.
2017-07-14 09:17:03,266: Correctly recognized files ['input/bms_135_yank_sol.inpcrd', 'input/bms_135_yank_sol.prmtop'] as ['inpcrd', 'prmtop']
2017-07-14 09:17:03,268: Correctly recognized files ['input/bms_135_yank_sol.inpcrd', 'input/bms_135_yank_sol.prmtop'] as ['inpcrd', 'prmtop']
2017-07-14 09:17:03,269: Wrong system file types provided.
Extensions provided: ['inpcrd', 'prmtop']
Expected extensions: ['gro', 'top']

And I can also get the opposite when I, for example, modify the extension to the gro/top combination, such that YANK gives this error:

2017-07-14 08:44:54,536: Setting OpenCL platform to use precision model 'mixed'.
2017-07-14 08:44:58,752: ERROR - yank.yamlbuild - Wrong system file types provided.
Extensions provided: ['gro', 'top']
Expected extensions: ['inpcrd', 'prmtop']
2017-07-14 08:44:58,754: ERROR - yank.yamlbuild - Wrong system file types provided.
Extensions provided: ['gro', 'top']
Expected extensions: ['inpcrd', 'prmtop']
2017-07-14 08:44:58,761: ERROR - yank.yamlbuild - Wrong system file types provided.
Extensions provided: ['gro', 'top']

My system is a protein/ligand complex solvated with TIP3P water and prepared with tleap and it runs with AMBER without a problem.
As I can understand, the phase1 input files are the inpcrd and prmtop files of the protein-ligand complex without water or counter ions, and phase2 input files are the solvating water molecule of this complex, which means that the box has the cavity that complements the phase 1 input specified in the first phase, is it true?
I have tried to work with the solvents sections as I could see in previous discussions, but it did not help, any clues?
Another question, if I do not specify the clearance keyword, YANK complaints, I am not sure if this value should be the one given for tleap while building the box or I need to measure it by VMD. Also, do I need to supply the originally built coordinates from tleap or I need to supply YANK with an equilibrated system, for example, after running some minimization and equilibration (NPT) in AMBER, and shall it be the rst7 format?

Thanks,
Marawan

**Comment by andrrizzi** [comment] 2017-07-14 15:38
Hi Marawan.

> I got this error

That error is actually normal and it's part of the script parsing. I thought I removed the printing but maybe I forgot. You don't have to worry about it though.

> the phase1 input files are the inpcrd and prmtop files of the protein-ligand complex without water or counter ions, and phase2 input files are the solvating water molecule of this complex

Not quite. Assuming you want to do a calculation in explicit solvent, the phase 1 input files must have protein-ligand complex + water + counterions, the phase 2 input files must have ligand + water + counterions (i.e. no receptor).

> I need to supply YANK with an equilibrated system, for example, after running some minimization and equilibration

You can tell YANK to minimize and equilibrate for you using the [`minimize` and `number_of_equilibration_iterations` options](http://getyank.org/0.16.2/yamlpages/options.html#minimize), but if you prefer to run those separately that also works! I don't think we support `.rst` files currently though, it'll have to be an `.inpcrd` file.

**Comment by mmagithub** [comment] 2017-07-14 18:09
Hello Andrea,
Thanks for the reply.
Still I am getting errors, I used the inputs the way you suggested by stripping the receptor atoms from phase 2 inputs, I can viualize the 4 systems (2 for phase 1 & 2 for phase 2) normally in VMD.
Here is the error I am getting:
######################
2017-07-14 12:04:04,205: Setting OpenCL platform to use precision model 'mixed'.
2017-07-14 12:04:07,556: ERROR - yank.yamlbuild - Wrong system file types provided.
Extensions provided: ['inpcrd', 'prmtop']
Expected extensions: ['gro', 'top']
2017-07-14 12:04:07,557: ERROR - yank.yamlbuild - Wrong system file types provided.
Extensions provided: ['inpcrd', 'prmtop']
Expected extensions: ['gro', 'top']
2017-07-14 12:04:07,558: ERROR - yank.yamlbuild - Wrong system file types provided.
Extensions provided: ['inpcrd', 'prmtop']
Expected extensions: ['pdb', 'xml']
2017-07-14 12:04:07,558: ERROR - yank.yamlbuild - System bms-135: _system_files(['input/P_t-BMS135_5J89_norec_solvated.inpcrd', 'input/P_t-BMS135_5J89_norec_solvated.prmtop']) raised YamlParseError("Wrong system file types provided.\nExtensions provided: ['inpcrd', 'prmtop']\nExpected extensions: ['pdb', 'xml']",)
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/bin/yank", line 11, in <module>
    load_entry_point('yank==0.16.2', 'console_scripts', 'yank')()
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/commands/script.py", line 97, in dispatch
    yaml_builder = YamlBuilder(yaml_source=yaml_path)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1329, in __init__
    self.parse(yaml_source)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1431, in parse
    self._db.systems = self._validate_systems(yaml_content.get('systems', {}))
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 2072, in _validate_systems
    raise YamlParseError('System {}: {}'.format(system_id, e.autos[-1]))
yank.yamlbuild.YamlParseError: System bms-135: _system_files(['input/P_t-BMS135_5J89_norec_solvated.inpcrd', 'input/P_t-BMS135_5J89_norec_solvated.prmtop']) raised YamlParseError("Wrong system file types provided.\nExtensions provided: ['inpcrd', 'prmtop']\nExpected extensions: ['pdb', 'xml']",)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
######################

Any clue?

Regards,
Marawan

**Comment by andrrizzi** [comment] 2017-07-14 19:00
Looking at the script at the top, I think it's because you're missing the `*` character in between number and units in `nonbonded_cutoff` and `clearance`.

Sorry for the uninformative message. We're still working on finding a way to combine easy parsing with meaningful errors.

**Comment by mmagithub** [comment] 2017-07-14 19:04
Hi Nndrea,
No it is there, but when I copy and paste it is gone in the HTML page for some reasons!
have you ever tested a system similar to what i am simulating, i mean ligand/protein solvated in AMBER?
I have checked openmm and it should read AMBER files without problems, do you think this might be a cause?

Regards,
Marawan

**Comment by andrrizzi** [comment] 2017-07-14 19:08
Can you post the full script using [this markdown syntax](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks)? This way everything should show up.

We've run several simulations using prepared AMBER files. That should be just a syntax error in the YAML script.

**Comment by mmagithub** [comment] 2017-07-14 19:19
I emailed the script to you, please let me know when you receive it.

Thanks in advance,
Marawan

**Comment by andrrizzi** [comment] 2017-07-14 19:30
In the script, you sent me I see
```
systems:
  bms-135:
    phase1_path:: [input/P_t-BMS135_5J89_com_solvated.inpcrd,input/P_t-BMS135_5J89_com_solvated.prmtop]
    phase2_path: [input/P_t-BMS135_5J89_norec_solvated.inpcrd,input/P_t-BMS135_5J89_norec_solvated.prmtop]
    ligand_dsl: resname MOL
    solvent_dsl: resname WAT 
    solvent: PME-solvent
```
There's an extra `:` after the keyword `phase1_path`. I think that's responsible for the parsing error.

Be aware that the `solvent_dsl` also needs to include counterions if you have them. That's an optional keyword though. If you leave it out, YANK should be able to automatically determine which atoms are waters and counterions.

**Comment by mmagithub** [comment] 2017-07-14 21:11
Thanks Andreas, this problem seems to be resolved.
Now the next issue is the system charges that I got complaining from. My protein has a charge of -2, the ligand is +1 then I needed to add 1 sodium to balance everything in AMBER. In YANK, i got this complain regarding what it seems to be charge imbalance,
#############
2017-07-14 14:19:03,041: Setting OpenCL platform to use precision model 'mixed'.
2017-07-14 14:19:06,890: Correctly recognized files ['input/P_t-BMS135_5J89_com_solvated.inpcrd', 'input/P_t-BMS135_5J89_com_solvated.prmtop'] as ['inpcrd', 'prmtop']
2017-07-14 14:19:06,892: Correctly recognized files ['input/P_t-BMS135_5J89_norec_solvated.inpcrd', 'input/P_t-BMS135_5J89_norec_solvated.prmtop'] as ['inpcrd', 'prmtop']
2017-07-14 14:19:06,911: Node 1/4: executing <function _check_resume at 0x2aaad556ff50>
2017-07-14 14:19:06,912: Node 1/4: waiting for barrier after <function _check_resume at 0x2aaad556ff50>
2017-07-14 14:19:07,315: Node 1/4: executing <function _setup_experiments at 0x2aaad5572230>
2017-07-14 14:19:07,315: Node 1/4: waiting for barrier after <function _setup_experiments at 0x2aaad5572230>
2017-07-14 14:19:07,316: Node 1/4: executing <function _safe_makedirs at 0x2aaad5572410>
2017-07-14 14:19:07,316: Node 1/4: waiting for barrier after <function _safe_makedirs at 0x2aaad5572410>
2017-07-14 14:19:07,317: Node 1/4: executing <bound method YamlBuilder._generate_yaml of <yank.yamlbuild.YamlBuilder object at 0x2aaad72dd5d0>>
2017-07-14 14:19:07,346: DSL string for the ligand: "resname MOL"
2017-07-14 14:19:07,346: DSL string for the solvent: "auto"
2017-07-14 14:19:07,347: Reading phase complex
2017-07-14 14:19:07,347: prmtop: input/P_t-BMS135_5J89_com_solvated.prmtop
2017-07-14 14:19:07,347: inpcrd: input/P_t-BMS135_5J89_com_solvated.inpcrd
Traceback (most recent call last):
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/bin/yank", line 11, in <module>
    load_entry_point('yank==0.16.2', 'console_scripts', 'yank')()
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/cli.py", line 71, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/commands/script.py", line 100, in dispatch
    yaml_builder.run_experiments()
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 1462, in run_experiments
    for experiment_index, experiment in enumerate(self._build_experiments()):
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 2392, in _build_experiments
    yield self._build_experiment(combination, output_dir)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yamlbuild.py", line 2668, in _build_experiment
    phase_protocol)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/yank.py", line 833, in _build_default_alchemical_region
    system, topography, alchemical_region_name)
  File "/cm/shared/apps/anaconda2/anaconda-4.4.0/lib/python2.7/site-packages/yank/pipeline.py", line 259, in find_alchemical_counterions
    region_name, mol_net_charge, ions_names_charges))
ValueError: Impossible to find a solution for region ligand_atoms. Net charge: 1, system ions: [('Na+', 1)].
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
#############
If I remove the receptor, then phase 2 will have a positive charge.
If the problem comes from phase 1 (the full system), do I need to do something special, or whatever AMBER thinks neutral should be also neutral in YANK?
I removed the solvent_dsl section as you suggested.
Last, what abou the keyword clearnace, has it to be explicitly specified even in AMBER formatted files.

**Comment by andrrizzi** [comment] 2017-07-14 21:18
The problem is when you are turning off the interactions of the positively charged ligand, YANK needs to turn off a _negatively_ charged counterion, otherwise there will be a net charge in the solvation box. You'll have to add 2 Na+ ions and 1 Cl- to make it happen (YANK automatically handles it if you go through the automatic pipeline).

> what abou the keyword clearnace

`clearance` is needed only if you go through the automatic pipeline (i.e. if you start from separate `pdb` receptor and `mol2` ligand) because YANK needs to know how many water molecules to add, but if you already provide solvated system files that info is ignored.

**Comment by mmagithub** [comment] 2017-07-14 23:06
Many thanks Andrea, It works now. But I need to run longer to get good results it seems. I will ask for feedback if I got stuck somewhere.
BTW, YANK can work normally with the rst7 files produced by AMBER. but you only need to change the extension to inpcrd. This is a side note that you may want to take into account.

**Comment by andrrizzi** [comment] 2017-07-14 23:09
> YANK can work normally with the rst7 files produced by AMBER. but you only need to change the extension to inpcrd.

Thanks for the tip!

Do you mind if I close the issue? You can open another one if you run into a new problem.

**Comment by mmagithub** [comment] 2017-07-14 23:16
Sure Andrea.

**Closed** 2017-07-15 00:32 UTC
