### ISSUE TITLE
YANK MPI runs sometimes hang

### ISSUE THREAD

**Issue by jchodera** [choderalab/yank#1088] opened 2018-09-13 18:28 UTC
I've observed this on a few different systems: Sometimes YANK MPI jobs hang and make no progress thereafter, having completed a `switch_experiment_interval` number of iterations. @andrrizzi suspects this may be related to our NaN handling.

**Comment by andrrizzi** [comment] 2018-10-13 16:39
Duplicate of #1109.

**Closed by andrrizzi** 2018-10-13 16:39 UTC
Labels: Priority medium, bug
