### ISSUE TITLE
how to run yank on MPI mode

### ISSUE THREAD

**Issue by naveenmeena584** [choderalab/yank#1042] opened 2018-07-18 10:43 UTC
yes just want to know how to run yank with MPI , i tried to copy paste command it not working, can you please help me out:
Running in serial mode
To run the simulation in serial mode, simply use yank script, specifying a yaml file by --yaml=filename.yaml:
Running in serial mode
$ yank script --yaml=yank.yaml

Running in MPI mode
Alternatively, to run the simulation in MPI mode:

$ mpirun yank script --yaml=yank.yaml

so i  am not able to use mpirun serial mode is working fine

**Comment by jchodera** [comment] 2018-07-19 08:45
Hi @naveenmeena584: Is there some text you meant to include with this issue? What specifically are you looking for help on?

**Comment by naveenmeena584** [comment] 2018-07-20 04:51
hi @ jchodera  please check now.

**Comment by jchodera** [comment] 2018-07-20 14:57
Can you provide any more information beyond "not working"? What kind of output do you see?

It's unfortunately very difficult for us to debug specifics of MPI problems on your particular system since this is not something we can reproduce locally. Do you have any other MPI programs you can run successfully on your system? How do you generally run them?

**Comment by jchodera** [comment] 2018-08-19 19:39
Closing this issue since no useful information was provided that would let us assess and debug the problem. Please reopen if you can provide this information!

**Closed by jchodera** 2018-08-19 19:39 UTC
