### ISSUE TITLE
Generated experiment.yaml missing entries

### ISSUE THREAD

**Issue by sgill2** [choderalab/yank#1014] opened 2018-06-14 13:45 UTC
After running `yank script -y some.yaml` (with yank 0.22.0) I noticed the generated ` experiments/experiment.yaml` file was missing some headings. In my case I specified `mcmc_moves` and `samplers`, but neither showed up in the resulting `experiment.yaml` script, (although the name given to the sampler did show up under
 ```
experiments:
     sampler: <sampler_name_here>
```
)

**Comment by jchodera** [comment] 2018-06-14 13:56
This is a duplicate of #947. @andrrizzi will address this soon, but it shouldn't affect the ability to run things at the moment.

**Comment by jchodera** [comment] 2018-06-14 13:57
Also, please update to yank 0.22.2!
https://github.com/choderalab/yank/releases

**Closed by jchodera** 2018-06-14 13:56 UTC
