### ISSUE TITLE
installing yank without anaconda

### ISSUE THREAD

**Issue by dprovasi** [choderalab/yank#284] opened 2015-07-09 15:10 UTC
Just a note on one tiny problem we had while installing yank directly (python 2.7.6) rather than via  anaconda, which might be useful for others forced to do the same.
We had to change the `setup.py` (line 132) `find_packages('yank')` to `find_packages('Yank')`.

All doctests passed succesfully during `yank selftest`,with only one (not yank-related, though) warning 

```
[kapooa03@interactive1 ~]$ yank selftest
Running doctests for all modules...
/hpc/packages/minerva-common/py_packages/2.7/lib/python2.7/site-packages/mdtraj/utils/validation.py:116: TypeCastPerformanceWarning: Casting Replica States dtype=int32 to <type 'numpy.int64'> 
  TypeCastPerformanceWarning)
All doctests pass.
```

**Comment by jchodera** [comment] 2015-07-09 15:17
Thanks! I will take a look.

**Comment by jchodera** [comment] 2016-06-07 22:36
This might be best fixed by renaming `Yank/` to `yank/`.

**Comment by Lnaden** [comment] 2016-11-08 16:26
Ensure this is fixed before 1.0.

**Comment by jchodera** [comment] 2016-11-09 02:00
How about we rename `Yank` to `yank` as part of our API refactor?

**Comment by andrrizzi** [comment] 2016-11-09 16:07
Sure! I can try to make it work.

**Comment by Lnaden** [comment] 2016-11-09 16:09
Im pretty sure I already fixed this back when I did the Python 3 refactor by using the relative imports. The note I made there was for me to double check that it had been fixed once I got to bug squashing instead of issue touching

**Comment by andrrizzi** [comment] 2016-11-09 16:14
Oh, awesome! Ok then.

**Comment by Lnaden** [comment] 2016-11-10 20:07
This should have been fixed when I did the Py3 refactor. I just tried to replicate through conda and local install and cannot reproduce. So I will close it and if its still an issue, we'll reopen it.

**Closed by Lnaden** 2016-11-10 20:07 UTC
Labels: Priority high
