### ISSUE TITLE
yank status failure

### ISSUE THREAD

**Issue by dtmoustakas** [choderalab/yank#1064] opened 2018-08-10 13:32 UTC
Hi,

I have a yank calculation consisting of a single protein and single ligand, running seemingly successfully on an Ubuntu 16.04 box with an NVIDIA K40 GPU.  The job has accumulated about 4000 iterations, and the log file doesn't appear to show any errors or warnings.  However, I've tried quite at quite a few points throughout the calculation to run "yank status -y filename.yaml", but receive the following error each time:

$ yank status -y sams-twostage-boresch-dense.yaml

2018-08-10 06:24:14,868: Setting CUDA platform to use precision model 'mixed'.
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 140189143320320:
  #000: H5F.c line 586 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1305 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1839 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 940 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
Traceback (most recent call last):
  File "/home/dmoustakas/miniconda/bin/yank", line 11, in <module>
    load_entry_point('yank==0.23.2', 'console_scripts', 'yank')()
  File "/home/dmoustakas/miniconda/lib/python3.6/site-packages/yank/cli.py", line 73, in main
    dispatched = getattr(commands, command).dispatch(command_args)
  File "/home/dmoustakas/miniconda/lib/python3.6/site-packages/yank/commands/status.py", line 93, in dispatch
    for exp_status in exp_builder.status():
  File "/home/dmoustakas/miniconda/lib/python3.6/site-packages/yank/experiment.py", line 880, in status
    phase_status = AlchemicalPhase.read_status(phase_nc_path)
  File "/home/dmoustakas/miniconda/lib/python3.6/site-packages/yank/yank.py", line 834, in read_status
    sampler_class = cls._read_sampler_class(storage)
  File "/home/dmoustakas/miniconda/lib/python3.6/site-packages/yank/yank.py", line 1241, in _read_sampler_class
    reporter.open(mode='r')
  File "/home/dmoustakas/miniconda/lib/python3.6/site-packages/yank/multistate/multistatereporter.py", line 276, in open
    primary_ncfiles['analysis'] = netcdf.Dataset(self._storage_file_analysis, mode, version=netcdf_format)
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'sams-twostage-boresch-dense/experiments/complex.nc'

Is this the result of having only one experiment in the calculation, so that the .nc file is always open and locked?

Thanks,
Demetri

**Comment by jchodera** [comment] 2018-08-10 13:38
We have seen this error before. In *principle*, NetCDF files are supposed to allow one process to be reading and another process to be writing at the same time. In practice, it appears that the patterns we are using in writing the NetCDF files somehow end up locking the file much of the time, causing read accesses (via `yank status` or `yank analyze`) to fail if the calculation is still running.

Once the calculation is terminated or ends, the `.nc` file should be available for status checks or analysis. Let us know if this isn't the case---we've seen occasional corruption, but have taken steps to minimize this.

We're working on designing a more robust storage strategy, but that will require a complete overhaul of the storage system that will have to wait a bit for the future.

**Comment by dtmoustakas** [comment] 2018-08-10 13:41
Thanks John, I'll probably stop the calculation at 10000 iterations, so I'll check again at that point and will let you know if the problem persists after yank has stopped running.

**Comment by jchodera** [comment] 2018-08-10 13:44
You might check out the [online analysis features](http://getyank.org/latest/yamlpages/samplers.html#yaml-samplers-online-analysis-parameters) which allow you to specify a target uncertainty via [`online_analysis_target_error`](http://getyank.org/latest/yamlpages/samplers.html#online-analysis-target-error), where the calculation will be terminated when a desired precision is reached.

**Comment by andrrizzi** [comment] 2018-08-10 13:48
I've implemented a workaround here #855, but I never merged it because I was never able to reproduce and test that it was working. Maybe we should just merge that PR though! It doesn't solve the locking problem, but at least it allows YANK to print the status of all the simulations with an unlocked netcdf database.

You can also try setting the environment variable `HDF5_USE_FILE_LOCKING=FALSE` (see the suggestion from @floriankrb in #855 that I think worked for him), although I'm not sure about the implications of changing that setting.

**Comment by Lnaden** [comment] 2018-08-10 13:50
I think i have tinkered with that environment variable before and it does not work well. But its been a while so maybe its been fixed?

**Comment by dtmoustakas** [comment] 2018-08-13 18:58
Just a quick update - I stopped the calculation when it passed 10K iterations, and at that point, the analysis works fine.  So I don't think there's any issue with corruption.  Thanks for all the suggestions!

**Closed** 2018-08-19 19:36 UTC
