### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by nividic** [choderalab/yank#235] opened 2015-06-03 19:05 UTC
Hi there,

I download the latest version of Yank by using GitHub (master branch) and I performed an installation from scratch (No anaconda). Running the installation program:

python setup.py install 

the installation procedure raise an OSError. The installation program is looking for the ‘yank’ directory not ‘Yank’. In order to overcome the issue as temporary solution I decided to copy the directory ‘Yank’ in ‘yank’. Therefore in my installation folder I had both directories. In this way the installation program was able to finish.

Gaetano

**Comment by jchodera** [comment] 2015-06-04 08:34
That's very odd.  What OS are you using?

We suggest you use anaconda.  The easiest way to install the Yank development version is to follow the instructions here:
http://getyank.org/latest/installation.html#development-build

**Comment by jchodera** [comment] 2015-06-04 08:35
> the installation procedure raise an OSError

Can you paste the whole error?

**Comment by nividic** [comment] 2015-06-04 16:32
Hi there. I'm using Ubuntu 14.04 LTS. The error is:

Traceback (most recent call last):
  File "setup.py", line 132, in <module>
    packages=['yank', "yank.tests", "yank.commands", "yank.mixing"] + ['yank.%s' % package for package in find_packages('yank')],
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 54, in find_packages
    for name in os.listdir(where):
OSError: [Errno 2] No such file or directory: 'yank'

Cheers,

Gaetano

**Comment by jchodera** [comment] 2015-06-05 04:36
That's odd.  I haven't seen this problem on `osx` or `linux`.

> The installation program is looking for the ‘yank’ directory not ‘Yank’

This line is supposed to cause it to look for `Yank`:
 ```
  package_dir={'yank': 'Yank'},
```
The directory was originally named `yank` but was changed to `Yank` because of some namespace issues that caused trouble with `version.py`...

**Comment by jchodera** [comment] 2015-06-17 00:44
Are you still having trouble with this?  Have you tried Anaconda Python (which can be installed locally)?

**Comment by andrrizzi** [comment] 2016-06-07 02:24
Duplicate of #284 that contains the solution. Closing this one.

**Closed by andrrizzi** 2016-06-07 02:24 UTC
