### ISSUE TITLE
Memory leak on GPU cluster

### ISSUE THREAD

**Issue by fsimkovic** [choderalab/yank#397] opened 2016-06-09 07:54 UTC
Running a simulation causes a memory leak. This problem becomes particularly noticeable in longer simulations with larger systems. Do you observe a similar behaviour on your systems? Any suggestions on the cause of this problem and how it can be resolved?

```
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   751549.69 sec.
    Max Memory :                                 9495.96 MB
    Average Memory :                             5074.54 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   80053 MB
    Max Processes :                              6
    Max Threads :                                33
    Run time :                                   1127583 sec.
    Turnaround time :                            1127584 sec.

The output (if any) follows:

=====================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 135
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
=====================================================================================
APPLICATION TERMINATED WITH THE EXIT STRING: Bus error (signal 7)
```

**Comment by jchodera** [comment] 2016-06-09 11:31
Is this actually a memory leak? The only indication is the large swap size of 80GB, which does strike me as large but is pretty small for modern hard drives, leading me to wonder why a Bus Error was triggered to cause exit. If the queue killed the job for exceeding memory resources, you usually get a different error.

Why was the job running for 13 days nonstop? We generally break our jobs into 24 hour chunks and chain them so as to be nice to our colleagues who also have to make use of the batch queue. Our batch queue limit is 48 hours, I believe, so we have never experienced this issue.

I'll see if we can figure OK it what the slow leak might be due to. I suspect it may be related to the NetCDF file handling but that is just a guess. We can do some profiling to see.

In the meantime you should be able to resume your jobs just fine. @andrizzi had added a resume flag to the YAML syntax (I think it is ‘resume: True‘) if you don't already have this in your YAML file. Don't delete your setup or NetCDF store files! It will append to them.

**Comment by fsimkovic** [comment] 2016-06-09 12:01
As far as I can tell it appears to be a memory leak. I started a YANK job yesterday which has - after 24h - tippled in %Mem usage (0.9% to 2.7%). Luckily, we have rarely run into trouble with long waiting times in the batch queue so we have never had the need to splitting jobs into chunks.

I haven't started jobs using the YAML syntax. Is there a way to do this from the command line (or within the source)? I don't necessarily want to construct the YAML files for a great number of jobs.

Your suggestion regarding the NetCDF file handling is what we believe to be the case too. We actually experience a very similar issue submitting OpenMM jobs directly (we will submit a separate issue to the OpenMM issue tracker and link it here). Is there a way around using the NetCDF parser?

**Comment by jchodera** [comment] 2016-06-09 12:32
Please submit an openmm issue with a simple example that demonstrates the issue!

If you are using the CLI, you should just be able to use the  "yank run ..." command (launched via mpirun, of course) to extend the simulation. Don't delete the store files and it should just resume where it left off. Try this with a short job first until you are comfortable with it.

The "yank setup amber..." CLI options are being deprecated in favor of the YAML files in the next release. Will that cause a problem for you guys? All our examples are being upgraded to the new YAML format because our is much more flexible.

**Comment by andrrizzi** [comment] 2016-06-09 14:33
I'll try to profile this to see if I can detect the origin of the issue. Thanks for reporting!

**Comment by jchodera** [comment] 2016-06-09 14:38
See also this issue:
https://github.com/pandegroup/openmm/issues/1513

**Comment by jchodera** [comment] 2016-06-09 14:40
I find a lot of old discussion threads (many of which are still open) when searching for "python netcdf4 memory leak", so this may indeed be it. It might be worth seeing if we can fix the [OpenMM issue](https://github.com/pandegroup/openmm/issues/1513) first with some `del` or `gc.cleanup()` calls in case it is Python's fault. If not, it may be the NetCDF C driver layer that is causing this.

**Comment by andrrizzi** [comment] 2016-06-09 14:43
I see, thanks for the link! I'll wait to see how that issues goes then.

**Comment by jchodera** [comment] 2016-06-14 16:42
https://github.com/pandegroup/openmm/issues/1513 was resolved by replacing the [`scipy` NetCDF interface](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.io.netcdf.netcdf_file.html) with the [`netcdf4`](http://unidata.github.io/netcdf4-python/) interface, so that is clearly not our issue since we use the latter.

Do you have time to look into this, @andrrizzi?

**Comment by andrrizzi** [comment] 2016-06-14 16:59
Sure!

**Comment by fsimkovic** [comment] 2016-06-14 21:42
Thanks guys. Much appreciate the efforts!

**Comment by Lnaden** [comment] 2016-11-08 17:10
@andrrizzi was this fixed with the alchemy PR?

**Comment by andrrizzi** [comment] 2016-11-08 17:27
I'm actually not sure, sorry. I didn't have time to reproduce it so far.

**Comment by jchodera** [comment] 2016-11-08 17:29
We suspect this is a NetCDF issue. Let's keep it open for now as a low-priority bug.

**Comment by Lnaden** [comment] 2017-09-19 12:20
I don't think this has been an issue since the API overhaul and the move to conda forge channel. We can revisit this if its still an issue.

**Closed by Lnaden** 2017-09-19 12:20 UTC
Labels: bug, Priority low
