### ISSUE TITLE
Poor convergence (and possible uncertainty underestimation) with short simulations of charged systems

### ISSUE THREAD

**Issue by renm1** [choderalab/yank#749] opened 2017-08-18 21:13 UTC
As you know, we're attempting to compare the performance of different restraint schemes in Yank. While running Yank to calculate binding free energy of a CB7 host/guest system in 3 different restraint conditions (flat-bottom, harmonic, and null), we got wildly different free energies for the different restraints schemes we tried. The specific case is taken from https://github.com/MobleyLab/benchmarksets/tree/nieldev/input_files and is binding of memantine [SMILES: CC12CC3CC(C1)(CC(C3)(C2)N)C] to CB7. Even more alarmingly, we noticed that even values for deltaG in solvent were dramatically different from each other after 500 iterations (238.968 +- 0.977 kT, 244.959 +- 1.013 kT, and 239.207 +- 1.066 kT, respectively).  After scratching our heads about what might be causing a discrepancy of 5 kT in solution (!) we began to worry about the fact that the guest is charged, so probably Yank is also modulating an ion at the same time. (Discrepancies were also large for the host-guest complex, but we were most troubled by the ligand-in-solution component.)

To further investigate, we ran the same binding protocol on a cyclodextrin host/guest system instead (a neutral complex) and the deltaG solvent values agreed across protocols. We believe the inconsistent values in the CB7 complex are due to poor convergence of ion sampling. We wanted to bring this issue to your attention, as if these results hold up, then convergence for charged guest binding may be quite difficult, and uncertainties may not be adequately captured by the error analysis.

We've attached input files to reproduce these cases:
[CB7-restraints.tar.gz](https://github.com/choderalab/yank/files/1235663/CB7-restraints.tar.gz)

Thanks,
Michelle 
(+ @davidlmobley)

**Comment by jchodera** [comment] 2017-08-18 21:23
Thanks for attaching the input files! My hypothesis is that the uncertainty might be underestimated for some reason. Are you able to extend the simulations to see if these get closer to concordance with more sampling?

I can't look at the input files on my phone, but my guess is you had 500 iterations * 1 ps/iteration, which would only be 0.5 ns/replica, which is very short. Could you try 20-100 ns/replica?

**Comment by jchodera** [comment] 2017-08-18 21:25
Also, were you able to generate the Jupyter health report notebooks? The plots in there may be useful for assessing replica mixing!

**Comment by davidlmobley** [comment] 2017-08-18 22:13
> I can't look at the input files on my phone, but my guess is you had 500 iterations * 1 ps/iteration, which would only be 0.5 ns/replica, which is very short. Could you try 20-100 ns/replica?

@jchodera - we're actually asking about the ligand-in-solution part, here, where presumably 20-100 ns/replica should not be necessary, unless we're missing something...? 

I certainly suspect that you are right and the uncertainty estimates are way too small, however. We've moved on to an uncharged guest for our benchmarking in this area but we wanted to send this your way since there could be implications for your protocol, and that of @andrrizzi for the Yank paper.

**Comment by jchodera** [comment] 2017-08-19 00:52
I certainly don't have any evidence that convergence won't require tens of nanoseconds per replica, but it should be easy to hammer out at least 100 ns/day/GPU, and having a good dataset guaranteed to be well sampled is the first step toward figuring out what is going on. This is the most experimental feature of Yank, so it wouldn't surprise me if extensive simulations are required to converge.

Are you using the auto determination of thermodynamic states?

**Comment by jchodera** [comment] 2017-08-19 00:53
Yank now supports specifying target uncertainties that determine how long the simulation will be run. Maybe you could try for something like 0.1 kcal/mol error?

**Comment by jchodera** [comment] 2017-08-19 00:54
Tagging @lnaden to take a look on Monday since @andrrizzi is traveling.

**Comment by jchodera** [comment] 2017-08-19 20:17
Finally had a chance to look at the input files. Some observations:
* You are using 500 iterations at the default 500 steps of 2 fs/step (1 ps) per iteration. While we don't have a lot of data quite yet, my guess would be 0.5 ns is probably at least 1-2 orders of magnitude less simulation time than required to converge estimates of the free energy of annihilating a salt pair. Recall that we choose a set of neutralizing counterions (added at random) to annihilate, so we in principle have to sample sufficiently long to completely decorrelate their positions many times in computing their annihilation free energy. That is unlikely to happen in 0.5 ns.
* The thermodynamic state spacing is not being automatically computed using the `auto` keyword (which appears to [still require documentation to be written](https://github.com/choderalab/yank/issues/751)). This could lead to poor thermodynamic state overlap and poor mixing.

I am concerned about the statistical error estimates being very wrong, however. Examining your post-analysis Jupyter notebooks or, better yet, the smaller NetCDF files generated for each experiment would be very helpful in determining what went wrong there. My suspicion is that we have few (if any) replica round-trips, resulting in an underestimate of the correlation time. I'll have to think about how we might be able to account for this in our estimate of the correlation time. In the worst case, we can simply raise red flags if an insufficient number of replica round-trips are observed.

**Comment by renm1** [comment] 2017-08-31 21:28
I should mention that I looked at a mixing figure from one of our previous simulations (using CB7 and the charged guest), which does catch and report the poor mixing.
<img width="801" alt="cb7-harmonic" src="https://user-images.githubusercontent.com/30665501/29945975-3b1c863e-8e58-11e7-88d9-c9e57488666f.png">

**Comment by jchodera** [comment] 2017-08-31 21:30
Yeah, that "infinite iterations" and two red states with no exchanges is a sure giveaway that something is not working well in this system.

**Comment by davidlmobley** [comment] 2017-08-31 21:41
Yep, thanks, @jchodera . Mostly this is an FYI -- as I said the other week we're not pursuing this specific system at this point, but presumably @andrrizzi is going to run into exactly these issues since this IS one of the systems you guys are using for the Yank benchmarks paper. 

It's very interesting to me that this is happening during the LJ phase of the calculations, where charges have been already modified. That's quite non-intuitive to me. It'll be interesting to see what you guys figure out.

Oh, also, it's worth noting that even the solvent case here gave us pretty poor answers even though the mixing report doesn't highlight obvious red flags. Looking at it, this makes sense to me though as there is a block of states at the lower right which seem to basically only mix among themselves, and not with the states upwards and towards the left.

**Comment by jchodera** [comment] 2017-08-31 22:59
> It's very interesting to me that this is happening during the LJ phase of the calculations, where charges have been already modified. That's quite non-intuitive to me. It'll be interesting to see what you guys figure out.

We've consistently had trouble with the cavity-creation part near small `lambda` values. This could be an issue with the exact softcore form we're using, and it would be great if you could take a look! I realize we don't have this documented with equations (I'll add an issue to make sure we do), but the default parameters we use are set [here](https://github.com/choderalab/openmmtools/blob/master/openmmtools/alchemy.py#L569-L576):
```
_ALCHEMICAL_REGION_ARGS = collections.OrderedDict([
    ('alchemical_atoms', None),
    ('alchemical_bonds', None),
    ('alchemical_angles', None),
    ('alchemical_torsions', None),
    ('annihilate_electrostatics', True),
    ('annihilate_sterics', False),
    ('softcore_alpha', 0.5), ('softcore_a', 1), ('softcore_b', 1), ('softcore_c', 6),
    ('softcore_beta', 0.0), ('softcore_d', 1), ('softcore_e', 1), ('softcore_f', 2)
])
```
This corresponds to the alpha=0.5 LJ 1-1-6 form from the [Michael Shirts paper](http://dx.doi.org/10.1063/1.3607597). Is this what you've been using with gromacs, and does the protocol look similar to what you have used in the past?

> Oh, also, it's worth noting that even the solvent case here gave us pretty poor answers even though the mixing report doesn't highlight obvious red flags.

Can you elaborate on what you mean by "gave us pretty poor answers"? Do you mean the variation between independent runs was much larger than that expected from the statistical errors?

>  Looking at it, this makes sense to me though as there is a block of states at the lower right which seem to basically only mix among themselves, and not with the states upwards and towards the left.

Yes, it does look like the mixing is pretty poor from the mixing matrix, but it would be better to see the actual replica state trajectories (which are also plotted in the notebook).

**Comment by davidlmobley** [comment] 2017-09-01 16:56
> Can you elaborate on what you mean by "gave us pretty poor answers"? Do you mean the variation between independent runs was much larger than that expected from the statistical errors?

Yes -- variation was larger than expected from statistical errors (though this was just when few iterations were run; we are not running longer for this system, as noted above). But I'm really referring primarily to the in-solvent data noted above: (238.968 +- 0.977 kT, 244.959 +- 1.013 kT, and 239.207 +- 1.066 kT, respectively, for three trials (with different restraints, but the restraints don't apply in solvent, so....))

**Comment by jchodera** [comment] 2017-09-01 17:00
The worst offender (238.968 +- 0.977 kT, 244.959 +- 1.013 kT) is a difference of 4.25*sigma, so that's pretty significantly different. We'll take a look and see what might be going on there. My guess is the correlation times are being underestimated.

**Comment by davidlmobley** [comment] 2017-09-01 17:11
Yes, my naive guess is that there is an ion which "binds" to the host in solution and doesn't come unstuck, or only does very rarely (or the other way around, starts off in solution and takes a long time to find the guest and stick to it).

Have you guys thought about a protocol where you restrain the ion you're going to disappear/insert out in bulk somewhere so that it definitely is far away that it won't interact with the receptor or ligand (and also take out receptor rotational and translational motion)? I worry that the "just let the ion do what it wants" protocol is asking for convergence problems.

**Comment by jchodera** [comment] 2017-09-01 18:40
> Have you guys thought about a protocol where you restrain the ion you're going to disappear/insert out in bulk somewhere so that it definitely is far away that it won't interact with the receptor or ligand (and also take out receptor rotational and translational motion)? I worry that the "just let the ion do what it wants" protocol is asking for convergence problems.

Our current roadmap plans are to add in the osmostat to both decorrelate the counterions and sample over the appropriate distribution of counterion pairs representative of bulk ion concentrations. 

Restraining the ion is an interesting idea, but we'd want to remove the bias this introduces.

A simpler near-term idea might be to (1) use a reasonably high salt concentration and (2) select an ion far from the complex to decouple.

**Comment by davidlmobley** [comment] 2017-09-01 18:53
Right, I agree with all of that. I'm pointing this out mostly because you're running precisely these calculations (currently with a salt concentration of 0 -- just neutralizing salt -- I believe) for the Yank benchmark paper, so presumably you're going to collide with these issues shortly.

**Comment by davidlmobley** [comment] 2017-09-01 18:54
(Not super enthusiastic about the "select an ion far from the complex to decouple" approach, because (a) this relies on NOT having a rare problematic event, and (b) it won't work as well for a "ligand in solvent" case where the boxes are much smaller and collisions will be more frequent.)

**Comment by jchodera** [comment] 2017-09-01 18:54
I believe we're running with an ionic strength of 50 mM:
https://github.com/choderalab/yank-benchmark/pull/1/files#diff-ee2120f85c8d1bbc8f46d55f86bc2d3bR62

**Comment by andrrizzi** [comment] 2019-01-18 15:37
This was very likely caused by the reweighting from direct space to reciprocal space PME, which should be fixed now with exact electrostatics.

**Closed by andrrizzi** 2019-01-18 15:37 UTC
Labels: question
